### ISSUE TITLE
Client-side Write Sanitization

### ISSUE THREAD

**Issue by arjunkalburgi** [askalburgi/CMPUT379ASSIGNMENT2#3]
If no input: keep waiting. 

If input: sanitize the formatting of the input and send message.

**Comment by arjunkalburgi** [comment]
**Sanitizing Format of Input**

- First char ? - a number - newline
- First char ! - a number (multiple digits) - a letter - a number (multiple digits) - multiple letters - newline
- First char @ -  a number (multiple digits) - a letter - a number (multiple digits) - multiple letters - newline

**Comment by arjunkalburgi** [comment]
New function "sanitize" @aseth99 put your stuff in there

**Comment by aseth99** [comment]
client side write:
"?123" will just send over "?123" for now, only if all the things after ? are digits, need to check to see if its above max size of entries still

"@123p7\nmessage" will print out entry number, length of message should be, actual message length, and message, need to make check to match length of message to actual message length, and also how to deal with the entry number. currently this will only send "message" to server, but can send over entire thing instead with small change once we figure out how to use entries.

and final else for none of the above, (else{check =0}) , but not adding that for now to make it easier for testing
